### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by phanijsp** [marcusasdgg/pooMAgnet#1]
Got here from your reddit post,
I see that you placed [keyManaga.jks](https://github.com/marcusasdgg/Mangnet/blob/master/app/keyManga.jks) in your app directory. Is this your google play store key? If so, you may need to remove it from GitHub and erase its trace to prevent any security issues.

**Comment by marcusasdgg** [comment]
Hello thank you for the concern, no this .jks key is not for google play store, it is just a simple self-signed key authentication to ignore a warning in the github pipeline when building an App release. I will probably move off this method in the future and manually add releases instead.

**Comment by phanijsp** [comment]
Got it!, I will go ahead and close this issue now.
